### ISSUE TITLE
How to write the import statement

### ISSUE THREAD

**Issue by teacii** [MichaelSolati/ng2meta#1]
Hi,

I am trying to use as documented. However, I am not able to write a valid import statement for this.
It also looks like there are not js files.

Do we need extra configuration to use this?

Sorry for being noob

Cheers

**Comment by MichaelSolati** [comment]
@teacii are you writing your Angular 2 application in JS? I had only written this in TypeScript and had not compiled it for JS. Mind you at some point I should...

**Comment by zachcd** [comment]
`import {NG2MetaService} from 'ng2meta';`

Typescript only.
